# Generated by Django 2.2.3 on 2019-09-10 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moviemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('book_date', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('seattype', models.CharField(max_length=20)),
                ('totalseat', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='moviename',
        ),
        migrations.AddField(
            model_name='movies',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='gprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='platinum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='pprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='sprice',
            field=models.IntegerField(default=0),
        ),
    ]
