# Generated by Django 2.2.3 on 2019-09-11 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moviemanager', '0003_auto_20190910_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='book_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='bookings',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='movie',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='totalseat',
            field=models.IntegerField(),
        ),
    ]
