# Generated by Django 2.2.3 on 2019-09-11 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemanager', '0004_auto_20190911_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
